### ISSUE TITLE
User Auth

### ISSUE THREAD

**Issue by mwmadsen67** [breakfasting/Gwaphics#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
  - [x] When errors are displayed, the form adjusts properly
- [x] Smooth, bug free navigation
  - [x] Login errors clears when switching from login form to sign up form (and vice-versa)
  - [x] Errors should display for both `/signup` and`/login`.
- [x] Adequate and appropriate seeds
  - [x] Demo Login Works

**Comment by breakfasting** [comment]
@mwmadsen67 Finished User Auth

**Comment by mwmadsen67** [comment]
great job!
